Secure deployments.

diff --git a/.github/workflows/deploy-images.yml b/.github/workflows/deploy-images.yml
--- a/.github/workflows/deploy-images.yml
+++ b/.github/workflows/deploy-images.yml
@@ -25,8 +25,8 @@ on:
       - ".changeset/**"
 
 permissions:
+  # Specific jobs already set packages: write permissions.
   contents: read
-  packages: write
 
 env:
   CI: true
@@ -57,6 +57,8 @@ jobs:
       packages: write
     needs:
       - security
+    env:
+      REF: ${{ github.ref }}
     strategy:
       matrix:
         include:
@@ -78,6 +80,13 @@ jobs:
           # Don't persist credentials to prevent credentials to be leaked on artifacts.
           persist-credentials: false
 
+      - name: Validate input
+        run: |
+          if [[ ! "$REF" =~ ^[a-zA-Z0-9/_@.-]+$ ]]; then
+            echo "Invalid REF format: $REF"
+            exit 1
+          fi
+
       - name: Log in to the Github Container registry
         uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3.6.0
         with:
@@ -88,7 +97,7 @@ jobs:
       - name: Check if should build
         id: should_build
         run: |
-          if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.event_name }}" == "pull_request" ]] || [[ "${{ github.ref }}" =~ ${{ matrix.tag_pattern }} ]]; then
+          if [[ "$REF" == "refs/heads/main" ]] || [[ "${{ github.event_name }}" == "pull_request" ]] || [[ "$REF" =~ ${{ matrix.tag_pattern }} ]]; then
             echo "build=true" >> "$GITHUB_OUTPUT"
           else
             echo "build=false" >> "$GITHUB_OUTPUT"
@@ -100,9 +109,9 @@ jobs:
         env:
           UNTRUSTED_GITHUB_REF_NAME: ${{ github.ref_name }} # E.g. my-app@1.0.0 - Always populated; contains the branch name, tag name, or ref name depending on the event type.
         run: |
-          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+          if [[ "$REF" == "refs/heads/main" ]]; then
             VERSION="latest"
-          elif [[ "${{ github.ref }}" =~ ${{ matrix.tag_pattern }} ]]; then
+          elif [[ "$REF" =~ ${{ matrix.tag_pattern }} ]]; then
             VERSION="${UNTRUSTED_GITHUB_REF_NAME#*@}" # Strip the prefix from the tag name in order to get the tag version only
           fi
           echo "value=${VERSION}" >> "$GITHUB_OUTPUT"
